### ISSUE TITLE
Unsorted List in Igniter Causes Persistent Diff on Unchanged Files (Showing diff every time run command)

### ISSUE THREAD

**Issue by shahryarjb** [ash-project/igniter#145]
Hello Igniter team, as you can see in the image below, every time I run the mix task command, it shows the diff again, even for a file that hasn’t changed.

![Screenshot 2024-11-06 at 12 02 14](https://github.com/user-attachments/assets/49f49b8b-19ae-46af-a86c-bfbd369ccd2c)

The scenario is like this: if a list is created and isn’t sorted before creation, when the igniter runs the second time, it displays the key places changes. However, if I sort the list before creating it with the igniter, it will remain consistent and won’t show the diff, as the two files and requests will be identical.

### Example:
```elixir
config =
  [
    {String.to_atom(item.name),
     [
       name: item.name,
       args: args,
       optional: item.necessary,
       necessary: item.optional
     ]}
  ]
  |> Enum.into([])

  
igniter
|> Igniter.create_new_file(direct_path <> ".exs", "#{inspect(config)}", on_exists: :overwrite)
```

If i change my function to this, I have no problem:
```elixir
args =
            if is_struct(item.args),
              do:
                item.args
                |> Map.from_struct()
                |> Map.to_list()
                |> Enum.reject(&match?({_, []}, &1))
                |> Enum.sort(), # I just add Enum.sort() before creating file
              else: []
```

\*\* Runtime

- Elixir version 1.17.2
- Erlang version OTP 27
- OS MacOs Sequoia
- Igniter version 0.4.5

### Ref
- https://discord.com/channels/711271361523351632/1253324141491261472/1303648906391064679

**Comment by zachallaun** [comment]
Thanks for the report!

There's a chance that this is related to #143, which was fixed in the just-release v0.4.6. Can you confirm that this issue still persists after upgrading Igniter to v0.4.6?

**Comment by shahryarjb** [comment]
Hi @zachallaun, I hope you are well.

![Screenshot 2024-11-06 at 19 50 13](https://github.com/user-attachments/assets/e75cf56e-03ae-4aa0-bec9-fdea780b2d22)

After downloading new version, and test as you see top image it formatted (my sorted list). after y and re-run it shows me again another diff. and re-run again.. it has not diff!! I do not know it is fixed completely or not

**Comment by zachallaun** [comment]
Thanks for trying that out! I definitely wouldn't call it fixed yet since it's still happening :)

To make sure I understand what's going on, you're generating this list from a map, right? I don't think there's any guarantee about map ordering. It sounds like what's happening is that, whenever the code is run, the map is converted to a list and then written, and then because the order is randomly different, you occasionally see a diff.

If the issue is fixed by adding an `Enum.sort`, I'm pretty confident this isn't an issue with Igniter, though I could be missing something!
